import { NextResponse } from "next/server";

// This file contains all Google Standard voices and their supported languages as of August 2025.
// Source: https://cloud.google.com/text-to-speech/docs/voices

// GET endpoint to return all supported Standard voices and languages
export async function GET() {
  return NextResponse.json({ voices: STANDARD_VOICES, languages: STANDARD_LANGUAGES });
}
// List of all unique Standard-supported languages (code and label)
export const STANDARD_LANGUAGES = [
    { code: 'af-ZA', label: 'Afrikaans (South Africa)' },
    { code: 'ar-XA', label: 'Arabic' },
    { code: 'bg-BG', label: 'Bulgarian (Bulgaria)' },
    { code: 'bn-IN', label: 'Bengali (India)' },
    { code: 'ca-ES', label: 'Catalan (Spain)' },
    { code: 'cmn-CN', label: 'Mandarin Chinese' },
    { code: 'cmn-TW', label: 'Mandarin Chinese' },
    { code: 'cs-CZ', label: 'Czech (Czech Republic)' },
    { code: 'da-DK', label: 'Danish (Denmark)' },
    { code: 'de-DE', label: 'German (Germany)' },
    { code: 'el-GR', label: 'Greek (Greece)' },
    { code: 'en-AU', label: 'English (Australia)' },
    { code: 'en-GB', label: 'English (UK)' },
    { code: 'en-IN', label: 'English (India)' },
    { code: 'en-US', label: 'English (US)' },
    { code: 'es-ES', label: 'Spanish (Spain)' },
    { code: 'es-US', label: 'Spanish (US)' },
    { code: 'eu-ES', label: 'Basque (Spain)' },
    { code: 'fi-FI', label: 'Finnish (Finland)' },
    { code: 'fil-PH', label: 'Filipino (Philippines)' },
    { code: 'fr-CA', label: 'French (Canada)' },
    { code: 'fr-FR', label: 'French (France)' },
    { code: 'gl-ES', label: 'Galician (Spain)' },
    { code: 'gu-IN', label: 'Gujarati (India)' },
    { code: 'he-IL', label: 'Hebrew (Israel)' },
    { code: 'hi-IN', label: 'Hindi (India)' },
    { code: 'hu-HU', label: 'Hungarian (Hungary)' },
    { code: 'id-ID', label: 'Indonesian (Indonesia)' },
    { code: 'is-IS', label: 'Icelandic (Iceland)' },
    { code: 'it-IT', label: 'Italian (Italy)' },
    { code: 'ja-JP', label: 'Japanese (Japan)' },
    { code: 'kn-IN', label: 'Kannada (India)' },
    { code: 'ko-KR', label: 'Korean (South Korea)' },
    { code: 'lt-LT', label: 'Lithuanian (Lithuania)' },
    { code: 'lv-LV', label: 'Latvian (Latvia)' },
    { code: 'ml-IN', label: 'Malayalam (India)' },
    { code: 'mr-IN', label: 'Marathi (India)' },
    { code: 'ms-MY', label: 'Malay (Malaysia)' },
    { code: 'nb-NO', label: 'Norwegian (Norway)' },
    { code: 'nl-BE', label: 'Dutch (Belgium)' },
    { code: 'nl-NL', label: 'Dutch (Netherlands)' },
    { code: 'pa-IN', label: 'Punjabi (India)' },
    { code: 'pl-PL', label: 'Polish (Poland)' },
    { code: 'pt-BR', label: 'Portuguese (Brazil)' },
    { code: 'pt-PT', label: 'Portuguese (Portugal)' },
    { code: 'ro-RO', label: 'Romanian (Romania)' },
    { code: 'ru-RU', label: 'Russian (Russia)' },
    { code: 'sk-SK', label: 'Slovak (Slovakia)' },
    { code: 'sr-RS', label: 'Serbian (Cyrillic)' },
    { code: 'sv-SE', label: 'Swedish (Sweden)' },
    { code: 'ta-IN', label: 'Tamil (India)' },
    { code: 'te-IN', label: 'Telugu (India)' },
    { code: 'th-TH', label: 'Thai (Thailand)' },
    { code: 'tr-TR', label: 'Turkish (Turkey)' },
    { code: 'uk-UA', label: 'Ukrainian (Ukraine)' },
    { code: 'ur-IN', label: 'Urdu (India)' },
    { code: 'vi-VN', label: 'Vietnamese (Vietnam)' },
    { code: 'yue-HK', label: 'Chinese (Hong Kong)' },
];
// This file contains all Google Standard voices and their supported languages as of August 2025.
// Source: https://cloud.google.com/text-to-speech/docs/voices

export const STANDARD_VOICES = [
  { name: 'af-ZA-Standard-A', languageCodes: ['af-ZA'], gender: 'FEMALE' },
  { name: 'ar-XA-Standard-A', languageCodes: ['ar-XA'], gender: 'FEMALE' },
  { name: 'ar-XA-Standard-B', languageCodes: ['ar-XA'], gender: 'MALE' },
  { name: 'ar-XA-Standard-C', languageCodes: ['ar-XA'], gender: 'MALE' },
  { name: 'ar-XA-Standard-D', languageCodes: ['ar-XA'], gender: 'FEMALE' },
  { name: 'bg-BG-Standard-B', languageCodes: ['bg-BG'], gender: 'FEMALE' },
  { name: 'bn-IN-Standard-A', languageCodes: ['bn-IN'], gender: 'FEMALE' },
  { name: 'bn-IN-Standard-B', languageCodes: ['bn-IN'], gender: 'MALE' },
  { name: 'bn-IN-Standard-C', languageCodes: ['bn-IN'], gender: 'FEMALE' },
  { name: 'bn-IN-Standard-D', languageCodes: ['bn-IN'], gender: 'MALE' },
  { name: 'ca-ES-Standard-B', languageCodes: ['ca-ES'], gender: 'FEMALE' },
  { name: 'cmn-CN-Standard-A', languageCodes: ['cmn-CN'], gender: 'FEMALE' },
  { name: 'cmn-CN-Standard-B', languageCodes: ['cmn-CN'], gender: 'MALE' },
  { name: 'cmn-CN-Standard-C', languageCodes: ['cmn-CN'], gender: 'MALE' },
  { name: 'cmn-CN-Standard-D', languageCodes: ['cmn-CN'], gender: 'FEMALE' },
  { name: 'cmn-TW-Standard-A', languageCodes: ['cmn-TW'], gender: 'FEMALE' },
  { name: 'cmn-TW-Standard-B', languageCodes: ['cmn-TW'], gender: 'MALE' },
  { name: 'cmn-TW-Standard-C', languageCodes: ['cmn-TW'], gender: 'MALE' },
  { name: 'cs-CZ-Standard-B', languageCodes: ['cs-CZ'], gender: 'FEMALE' },
  { name: 'da-DK-Standard-F', languageCodes: ['da-DK'], gender: 'FEMALE' },
  { name: 'da-DK-Standard-G', languageCodes: ['da-DK'], gender: 'MALE' },
  { name: 'de-DE-Standard-G', languageCodes: ['de-DE'], gender: 'FEMALE' },
  { name: 'de-DE-Standard-H', languageCodes: ['de-DE'], gender: 'MALE' },
  { name: 'el-GR-Standard-B', languageCodes: ['el-GR'], gender: 'FEMALE' },
  { name: 'en-AU-Standard-A', languageCodes: ['en-AU'], gender: 'FEMALE' },
  { name: 'en-AU-Standard-B', languageCodes: ['en-AU'], gender: 'MALE' },
  { name: 'en-AU-Standard-C', languageCodes: ['en-AU'], gender: 'FEMALE' },
  { name: 'en-AU-Standard-D', languageCodes: ['en-AU'], gender: 'MALE' },
  { name: 'en-GB-Standard-A', languageCodes: ['en-GB'], gender: 'FEMALE' },
  { name: 'en-GB-Standard-B', languageCodes: ['en-GB'], gender: 'MALE' },
  { name: 'en-GB-Standard-C', languageCodes: ['en-GB'], gender: 'FEMALE' },
  { name: 'en-GB-Standard-D', languageCodes: ['en-GB'], gender: 'MALE' },
  { name: 'en-GB-Standard-F', languageCodes: ['en-GB'], gender: 'FEMALE' },
  { name: 'en-GB-Standard-N', languageCodes: ['en-GB'], gender: 'FEMALE' },
  { name: 'en-GB-Standard-O', languageCodes: ['en-GB'], gender: 'MALE' },
  { name: 'en-IN-Standard-A', languageCodes: ['en-IN'], gender: 'FEMALE' },
  { name: 'en-IN-Standard-B', languageCodes: ['en-IN'], gender: 'MALE' },
  { name: 'en-IN-Standard-C', languageCodes: ['en-IN'], gender: 'MALE' },
  { name: 'en-IN-Standard-D', languageCodes: ['en-IN'], gender: 'FEMALE' },
  { name: 'en-IN-Standard-E', languageCodes: ['en-IN'], gender: 'FEMALE' },
  { name: 'en-IN-Standard-F', languageCodes: ['en-IN'], gender: 'MALE' },
  { name: 'en-US-Standard-A', languageCodes: ['en-US'], gender: 'MALE' },
  { name: 'en-US-Standard-B', languageCodes: ['en-US'], gender: 'MALE' },
  { name: 'en-US-Standard-C', languageCodes: ['en-US'], gender: 'FEMALE' },
  { name: 'en-US-Standard-D', languageCodes: ['en-US'], gender: 'MALE' },
  { name: 'en-US-Standard-E', languageCodes: ['en-US'], gender: 'FEMALE' },
  { name: 'en-US-Standard-F', languageCodes: ['en-US'], gender: 'FEMALE' },
  { name: 'en-US-Standard-G', languageCodes: ['en-US'], gender: 'FEMALE' },
  { name: 'en-US-Standard-H', languageCodes: ['en-US'], gender: 'FEMALE' },
  { name: 'en-US-Standard-I', languageCodes: ['en-US'], gender: 'MALE' },
  { name: 'en-US-Standard-J', languageCodes: ['en-US'], gender: 'MALE' },
  { name: 'es-ES-Standard-E', languageCodes: ['es-ES'], gender: 'MALE' },
  { name: 'es-ES-Standard-F', languageCodes: ['es-ES'], gender: 'FEMALE' },
  { name: 'es-ES-Standard-G', languageCodes: ['es-ES'], gender: 'MALE' },
  { name: 'es-ES-Standard-H', languageCodes: ['es-ES'], gender: 'FEMALE' },
  { name: 'es-US-Standard-A', languageCodes: ['es-US'], gender: 'FEMALE' },
  { name: 'es-US-Standard-B', languageCodes: ['es-US'], gender: 'MALE' },
  { name: 'es-US-Standard-C', languageCodes: ['es-US'], gender: 'MALE' },
  { name: 'eu-ES-Standard-B', languageCodes: ['eu-ES'], gender: 'FEMALE' },
  { name: 'fi-FI-Standard-B', languageCodes: ['fi-FI'], gender: 'FEMALE' },
  { name: 'fil-PH-Standard-A', languageCodes: ['fil-PH'], gender: 'FEMALE' },
  { name: 'fil-PH-Standard-B', languageCodes: ['fil-PH'], gender: 'FEMALE' },
  { name: 'fil-PH-Standard-C', languageCodes: ['fil-PH'], gender: 'MALE' },
  { name: 'fil-PH-Standard-D', languageCodes: ['fil-PH'], gender: 'MALE' },
  { name: 'fr-CA-Standard-A', languageCodes: ['fr-CA'], gender: 'FEMALE' },
  { name: 'fr-CA-Standard-B', languageCodes: ['fr-CA'], gender: 'MALE' },
  { name: 'fr-CA-Standard-C', languageCodes: ['fr-CA'], gender: 'FEMALE' },
  { name: 'fr-CA-Standard-D', languageCodes: ['fr-CA'], gender: 'MALE' },
  { name: 'fr-FR-Standard-F', languageCodes: ['fr-FR'], gender: 'FEMALE' },
  { name: 'fr-FR-Standard-G', languageCodes: ['fr-FR'], gender: 'MALE' },
  { name: 'gl-ES-Standard-B', languageCodes: ['gl-ES'], gender: 'FEMALE' },
  { name: 'gu-IN-Standard-A', languageCodes: ['gu-IN'], gender: 'FEMALE' },
  { name: 'gu-IN-Standard-B', languageCodes: ['gu-IN'], gender: 'MALE' },
  { name: 'gu-IN-Standard-C', languageCodes: ['gu-IN'], gender: 'FEMALE' },
  { name: 'gu-IN-Standard-D', languageCodes: ['gu-IN'], gender: 'MALE' },
  { name: 'he-IL-Standard-A', languageCodes: ['he-IL'], gender: 'FEMALE' },
  { name: 'he-IL-Standard-B', languageCodes: ['he-IL'], gender: 'MALE' },
  { name: 'he-IL-Standard-C', languageCodes: ['he-IL'], gender: 'FEMALE' },
  { name: 'he-IL-Standard-D', languageCodes: ['he-IL'], gender: 'MALE' },
  { name: 'hi-IN-Standard-A', languageCodes: ['hi-IN'], gender: 'FEMALE' },
  { name: 'hi-IN-Standard-B', languageCodes: ['hi-IN'], gender: 'MALE' },
  { name: 'hi-IN-Standard-C', languageCodes: ['hi-IN'], gender: 'MALE' },
  { name: 'hi-IN-Standard-D', languageCodes: ['hi-IN'], gender: 'FEMALE' },
  { name: 'hi-IN-Standard-E', languageCodes: ['hi-IN'], gender: 'FEMALE' },
  { name: 'hi-IN-Standard-F', languageCodes: ['hi-IN'], gender: 'MALE' },
  { name: 'hu-HU-Standard-B', languageCodes: ['hu-HU'], gender: 'FEMALE' },
  { name: 'id-ID-Standard-A', languageCodes: ['id-ID'], gender: 'FEMALE' },
  { name: 'id-ID-Standard-B', languageCodes: ['id-ID'], gender: 'MALE' },
  { name: 'id-ID-Standard-C', languageCodes: ['id-ID'], gender: 'MALE' },
  { name: 'id-ID-Standard-D', languageCodes: ['id-ID'], gender: 'FEMALE' },
  { name: 'is-IS-Standard-B', languageCodes: ['is-IS'], gender: 'FEMALE' },
  { name: 'it-IT-Standard-E', languageCodes: ['it-IT'], gender: 'FEMALE' },
  { name: 'it-IT-Standard-F', languageCodes: ['it-IT'], gender: 'MALE' },
  { name: 'ja-JP-Standard-A', languageCodes: ['ja-JP'], gender: 'FEMALE' },
  { name: 'ja-JP-Standard-B', languageCodes: ['ja-JP'], gender: 'FEMALE' },
  { name: 'ja-JP-Standard-C', languageCodes: ['ja-JP'], gender: 'MALE' },
  { name: 'ja-JP-Standard-D', languageCodes: ['ja-JP'], gender: 'MALE' },
  { name: 'kn-IN-Standard-A', languageCodes: ['kn-IN'], gender: 'FEMALE' },
  { name: 'kn-IN-Standard-B', languageCodes: ['kn-IN'], gender: 'MALE' },
  { name: 'kn-IN-Standard-C', languageCodes: ['kn-IN'], gender: 'FEMALE' },
  { name: 'kn-IN-Standard-D', languageCodes: ['kn-IN'], gender: 'MALE' },
  { name: 'ko-KR-Standard-A', languageCodes: ['ko-KR'], gender: 'FEMALE' },
  { name: 'ko-KR-Standard-B', languageCodes: ['ko-KR'], gender: 'FEMALE' },
  { name: 'ko-KR-Standard-C', languageCodes: ['ko-KR'], gender: 'MALE' },
  { name: 'ko-KR-Standard-D', languageCodes: ['ko-KR'], gender: 'MALE' },
  { name: 'lt-LT-Standard-B', languageCodes: ['lt-LT'], gender: 'MALE' },
  { name: 'lv-LV-Standard-B', languageCodes: ['lv-LV'], gender: 'MALE' },
  { name: 'ml-IN-Standard-A', languageCodes: ['ml-IN'], gender: 'FEMALE' },
  { name: 'ml-IN-Standard-B', languageCodes: ['ml-IN'], gender: 'MALE' },
  { name: 'ml-IN-Standard-C', languageCodes: ['ml-IN'], gender: 'FEMALE' },
  { name: 'ml-IN-Standard-D', languageCodes: ['ml-IN'], gender: 'MALE' },
  { name: 'mr-IN-Standard-A', languageCodes: ['mr-IN'], gender: 'FEMALE' },
  { name: 'mr-IN-Standard-B', languageCodes: ['mr-IN'], gender: 'MALE' },
  { name: 'mr-IN-Standard-C', languageCodes: ['mr-IN'], gender: 'FEMALE' },
  { name: 'ms-MY-Standard-A', languageCodes: ['ms-MY'], gender: 'FEMALE' },
  { name: 'ms-MY-Standard-B', languageCodes: ['ms-MY'], gender: 'MALE' },
  { name: 'ms-MY-Standard-C', languageCodes: ['ms-MY'], gender: 'FEMALE' },
  { name: 'ms-MY-Standard-D', languageCodes: ['ms-MY'], gender: 'MALE' },
  { name: 'nb-NO-Standard-F', languageCodes: ['nb-NO'], gender: 'FEMALE' },
  { name: 'nb-NO-Standard-G', languageCodes: ['nb-NO'], gender: 'MALE' },
  { name: 'nl-BE-Standard-C', languageCodes: ['nl-BE'], gender: 'FEMALE' },
  { name: 'nl-BE-Standard-D', languageCodes: ['nl-BE'], gender: 'MALE' },
  { name: 'nl-NL-Standard-F', languageCodes: ['nl-NL'], gender: 'FEMALE' },
  { name: 'nl-NL-Standard-G', languageCodes: ['nl-NL'], gender: 'MALE' },
  { name: 'pa-IN-Standard-A', languageCodes: ['pa-IN'], gender: 'FEMALE' },
  { name: 'pa-IN-Standard-B', languageCodes: ['pa-IN'], gender: 'MALE' },
  { name: 'pa-IN-Standard-C', languageCodes: ['pa-IN'], gender: 'FEMALE' },
  { name: 'pa-IN-Standard-D', languageCodes: ['pa-IN'], gender: 'MALE' },
  { name: 'pl-PL-Standard-F', languageCodes: ['pl-PL'], gender: 'FEMALE' },
  { name: 'pl-PL-Standard-G', languageCodes: ['pl-PL'], gender: 'MALE' },
  { name: 'pt-BR-Standard-A', languageCodes: ['pt-BR'], gender: 'FEMALE' },
  { name: 'pt-BR-Standard-B', languageCodes: ['pt-BR'], gender: 'MALE' },
  { name: 'pt-BR-Standard-C', languageCodes: ['pt-BR'], gender: 'FEMALE' },
  { name: 'pt-BR-Standard-D', languageCodes: ['pt-BR'], gender: 'FEMALE' },
  { name: 'pt-BR-Standard-E', languageCodes: ['pt-BR'], gender: 'MALE' },
  { name: 'pt-PT-Standard-E', languageCodes: ['pt-PT'], gender: 'FEMALE' },
  { name: 'pt-PT-Standard-F', languageCodes: ['pt-PT'], gender: 'MALE' },
  { name: 'ro-RO-Standard-B', languageCodes: ['ro-RO'], gender: 'FEMALE' },
  { name: 'ru-RU-Standard-A', languageCodes: ['ru-RU'], gender: 'FEMALE' },
  { name: 'ru-RU-Standard-B', languageCodes: ['ru-RU'], gender: 'MALE' },
  { name: 'ru-RU-Standard-C', languageCodes: ['ru-RU'], gender: 'FEMALE' },
  { name: 'ru-RU-Standard-D', languageCodes: ['ru-RU'], gender: 'MALE' },
  { name: 'ru-RU-Standard-E', languageCodes: ['ru-RU'], gender: 'FEMALE' },
  { name: 'sk-SK-Standard-B', languageCodes: ['sk-SK'], gender: 'FEMALE' },
  { name: 'sr-RS-Standard-B', languageCodes: ['sr-RS'], gender: 'FEMALE' },
  { name: 'sv-SE-Standard-A', languageCodes: ['sv-SE'], gender: 'FEMALE' },
  { name: 'sv-SE-Standard-B', languageCodes: ['sv-SE'], gender: 'FEMALE' },
  { name: 'sv-SE-Standard-C', languageCodes: ['sv-SE'], gender: 'FEMALE' },
  { name: 'sv-SE-Standard-D', languageCodes: ['sv-SE'], gender: 'MALE' },
  { name: 'sv-SE-Standard-E', languageCodes: ['sv-SE'], gender: 'MALE' },
  { name: 'sv-SE-Standard-F', languageCodes: ['sv-SE'], gender: 'FEMALE' },
  { name: 'sv-SE-Standard-G', languageCodes: ['sv-SE'], gender: 'MALE' },
  { name: 'ta-IN-Standard-A', languageCodes: ['ta-IN'], gender: 'FEMALE' },
  { name: 'ta-IN-Standard-B', languageCodes: ['ta-IN'], gender: 'MALE' },
  { name: 'ta-IN-Standard-C', languageCodes: ['ta-IN'], gender: 'FEMALE' },
  { name: 'ta-IN-Standard-D', languageCodes: ['ta-IN'], gender: 'MALE' },
  { name: 'te-IN-Standard-A', languageCodes: ['te-IN'], gender: 'FEMALE' },
  { name: 'te-IN-Standard-B', languageCodes: ['te-IN'], gender: 'MALE' },
  { name: 'te-IN-Standard-C', languageCodes: ['te-IN'], gender: 'FEMALE' },
  { name: 'te-IN-Standard-D', languageCodes: ['te-IN'], gender: 'MALE' },
  { name: 'th-TH-Standard-A', languageCodes: ['th-TH'], gender: 'FEMALE' },
  { name: 'tr-TR-Standard-A', languageCodes: ['tr-TR'], gender: 'FEMALE' },
  { name: 'tr-TR-Standard-B', languageCodes: ['tr-TR'], gender: 'MALE' },
  { name: 'tr-TR-Standard-C', languageCodes: ['tr-TR'], gender: 'FEMALE' },
  { name: 'tr-TR-Standard-D', languageCodes: ['tr-TR'], gender: 'FEMALE' },
  { name: 'tr-TR-Standard-E', languageCodes: ['tr-TR'], gender: 'MALE' },
  { name: 'uk-UA-Standard-B', languageCodes: ['uk-UA'], gender: 'FEMALE' },
  { name: 'ur-IN-Standard-A', languageCodes: ['ur-IN'], gender: 'FEMALE' },
  { name: 'ur-IN-Standard-B', languageCodes: ['ur-IN'], gender: 'MALE' },
  { name: 'vi-VN-Standard-A', languageCodes: ['vi-VN'], gender: 'FEMALE' },
  { name: 'vi-VN-Standard-B', languageCodes: ['vi-VN'], gender: 'MALE' },
  { name: 'vi-VN-Standard-C', languageCodes: ['vi-VN'], gender: 'FEMALE' },
  { name: 'vi-VN-Standard-D', languageCodes: ['vi-VN'], gender: 'MALE' },
  { name: 'yue-HK-Standard-A', languageCodes: ['yue-HK'], gender: 'FEMALE' },
  { name: 'yue-HK-Standard-B', languageCodes: ['yue-HK'], gender: 'MALE' },
  { name: 'yue-HK-Standard-C', languageCodes: ['yue-HK'], gender: 'FEMALE' },
  { name: 'yue-HK-Standard-D', languageCodes: ['yue-HK'], gender: 'MALE' },
];

