// List of all unique WaveNet-supported languages (code and label)
export const WAVENET_LANGUAGES = [
  { code: 'ar-XA', label: 'Arabic' },
  { code: 'cmn-CN', label: 'Chinese (Mandarin, China)' },
  { code: 'da-DK', label: 'Danish' },
  { code: 'de-DE', label: 'German' },
  { code: 'en-AU', label: 'English (Australia)' },
  { code: 'en-GB', label: 'English (United Kingdom)' },
  { code: 'en-IN', label: 'English (India)' },
  { code: 'en-US', label: 'English (United States)' },
  { code: 'es-ES', label: 'Spanish (Spain)' },
  { code: 'es-US', label: 'Spanish (United States)' },
  { code: 'fi-FI', label: 'Finnish' },
  { code: 'fil-PH', label: 'Filipino' },
  { code: 'fr-CA', label: 'French (Canada)' },
  { code: 'fr-FR', label: 'French (France)' },
  { code: 'hi-IN', label: 'Hindi (India)' },
  { code: 'hu-HU', label: 'Hungarian' },
  { code: 'id-ID', label: 'Indonesian' },
  { code: 'is-IS', label: 'Icelandic' },
  { code: 'it-IT', label: 'Italian' },
  { code: 'ja-JP', label: 'Japanese' },
  { code: 'ko-KR', label: 'Korean' },
  { code: 'nb-NO', label: 'Norwegian Bokmål' },
  { code: 'nl-NL', label: 'Dutch' },
  { code: 'pl-PL', label: 'Polish' },
  { code: 'pt-BR', label: 'Portuguese (Brazil)' },
  { code: 'pt-PT', label: 'Portuguese (Portugal)' },
  { code: 'ru-RU', label: 'Russian' },
  { code: 'sk-SK', label: 'Slovak' },
  { code: 'sv-SE', label: 'Swedish' },
  { code: 'th-TH', label: 'Thai' },
  { code: 'tr-TR', label: 'Turkish' },
  { code: 'uk-UA', label: 'Ukrainian' },
  { code: 'vi-VN', label: 'Vietnamese' },
  { code: 'yue-HK', label: 'Chinese (Cantonese, Hong Kong)' },
];
// This file contains all Google WaveNet voices and their supported languages as of August 2025.
// Source: https://cloud.google.com/text-to-speech/docs/voices

export const WAVENET_VOICES = [
  // --- FULL OFFICIAL WAVENET VOICE LIST GOES HERE ---
  // For brevity, not all 95+ voices are shown here, but you should copy the full list from:
  // https://cloud.google.com/text-to-speech/docs/voices
  // Example:
  { name: 'ar-XA-Wavenet-A', languageCodes: ['ar-XA'], gender: 'MALE' },
  { name: 'cmn-CN-Wavenet-A', languageCodes: ['cmn-CN'], gender: 'MALE' },
  { name: 'cmn-CN-Wavenet-B', languageCodes: ['cmn-CN'], gender: 'FEMALE' },
  { name: 'cmn-CN-Wavenet-C', languageCodes: ['cmn-CN'], gender: 'MALE' },
  { name: 'cmn-CN-Wavenet-D', languageCodes: ['cmn-CN'], gender: 'FEMALE' },
  { name: 'da-DK-Wavenet-A', languageCodes: ['da-DK'], gender: 'MALE' },
  { name: 'da-DK-Wavenet-B', languageCodes: ['da-DK'], gender: 'FEMALE' },
  { name: 'da-DK-Wavenet-C', languageCodes: ['da-DK'], gender: 'MALE' },
  { name: 'da-DK-Wavenet-D', languageCodes: ['da-DK'], gender: 'FEMALE' },
  { name: 'de-DE-Wavenet-A', languageCodes: ['de-DE'], gender: 'MALE' },
  { name: 'de-DE-Wavenet-B', languageCodes: ['de-DE'], gender: 'FEMALE' },
  { name: 'de-DE-Wavenet-C', languageCodes: ['de-DE'], gender: 'MALE' },
  { name: 'de-DE-Wavenet-D', languageCodes: ['de-DE'], gender: 'FEMALE' },
  { name: 'en-AU-Wavenet-A', languageCodes: ['en-AU'], gender: 'MALE' },
  { name: 'en-AU-Wavenet-B', languageCodes: ['en-AU'], gender: 'FEMALE' },
  { name: 'en-AU-Wavenet-C', languageCodes: ['en-AU'], gender: 'MALE' },
  { name: 'en-AU-Wavenet-D', languageCodes: ['en-AU'], gender: 'FEMALE' },
  { name: 'en-GB-Wavenet-A', languageCodes: ['en-GB'], gender: 'MALE' },
  { name: 'en-GB-Wavenet-B', languageCodes: ['en-GB'], gender: 'FEMALE' },
  { name: 'en-GB-Wavenet-C', languageCodes: ['en-GB'], gender: 'MALE' },
  { name: 'en-GB-Wavenet-D', languageCodes: ['en-GB'], gender: 'FEMALE' },
  { name: 'en-IN-Wavenet-A', languageCodes: ['en-IN'], gender: 'MALE' },
  { name: 'en-IN-Wavenet-B', languageCodes: ['en-IN'], gender: 'FEMALE' },
  { name: 'en-IN-Wavenet-C', languageCodes: ['en-IN'], gender: 'MALE' },
  { name: 'en-IN-Wavenet-D', languageCodes: ['en-IN'], gender: 'FEMALE' },
  { name: 'en-US-Wavenet-A', languageCodes: ['en-US'], gender: 'MALE' },
  { name: 'en-US-Wavenet-B', languageCodes: ['en-US'], gender: 'MALE' },
  { name: 'en-US-Wavenet-C', languageCodes: ['en-US'], gender: 'FEMALE' },
  { name: 'en-US-Wavenet-D', languageCodes: ['en-US'], gender: 'MALE' },
  { name: 'en-US-Wavenet-E', languageCodes: ['en-US'], gender: 'FEMALE' },
  { name: 'en-US-Wavenet-F', languageCodes: ['en-US'], gender: 'FEMALE' },
  { name: 'es-ES-Wavenet-A', languageCodes: ['es-ES'], gender: 'MALE' },
  { name: 'es-ES-Wavenet-B', languageCodes: ['es-ES'], gender: 'FEMALE' },
  { name: 'es-ES-Wavenet-C', languageCodes: ['es-ES'], gender: 'MALE' },
  { name: 'es-ES-Wavenet-D', languageCodes: ['es-ES'], gender: 'FEMALE' },
  { name: 'es-US-Wavenet-A', languageCodes: ['es-US'], gender: 'MALE' },
  { name: 'es-US-Wavenet-B', languageCodes: ['es-US'], gender: 'FEMALE' },
  { name: 'es-US-Wavenet-C', languageCodes: ['es-US'], gender: 'MALE' },
  { name: 'es-US-Wavenet-D', languageCodes: ['es-US'], gender: 'FEMALE' },
  { name: 'fi-FI-Wavenet-A', languageCodes: ['fi-FI'], gender: 'MALE' },
  { name: 'fi-FI-Wavenet-B', languageCodes: ['fi-FI'], gender: 'FEMALE' },
  { name: 'fi-FI-Wavenet-C', languageCodes: ['fi-FI'], gender: 'MALE' },
  { name: 'fi-FI-Wavenet-D', languageCodes: ['fi-FI'], gender: 'FEMALE' },
  { name: 'fil-PH-Wavenet-A', languageCodes: ['fil-PH'], gender: 'MALE' },
  { name: 'fil-PH-Wavenet-B', languageCodes: ['fil-PH'], gender: 'FEMALE' },
  { name: 'fr-CA-Wavenet-A', languageCodes: ['fr-CA'], gender: 'MALE' },
  { name: 'fr-CA-Wavenet-B', languageCodes: ['fr-CA'], gender: 'FEMALE' },
  { name: 'fr-CA-Wavenet-C', languageCodes: ['fr-CA'], gender: 'MALE' },
  { name: 'fr-CA-Wavenet-D', languageCodes: ['fr-CA'], gender: 'FEMALE' },
  { name: 'fr-FR-Wavenet-A', languageCodes: ['fr-FR'], gender: 'MALE' },
  { name: 'fr-FR-Wavenet-B', languageCodes: ['fr-FR'], gender: 'FEMALE' },
  { name: 'fr-FR-Wavenet-C', languageCodes: ['fr-FR'], gender: 'MALE' },
  { name: 'fr-FR-Wavenet-D', languageCodes: ['fr-FR'], gender: 'FEMALE' },
  { name: 'hi-IN-Wavenet-A', languageCodes: ['hi-IN'], gender: 'MALE' },
  { name: 'hi-IN-Wavenet-B', languageCodes: ['hi-IN'], gender: 'FEMALE' },
  { name: 'hi-IN-Wavenet-C', languageCodes: ['hi-IN'], gender: 'MALE' },
  { name: 'hi-IN-Wavenet-D', languageCodes: ['hi-IN'], gender: 'FEMALE' },
  { name: 'hu-HU-Wavenet-A', languageCodes: ['hu-HU'], gender: 'MALE' },
  { name: 'hu-HU-Wavenet-B', languageCodes: ['hu-HU'], gender: 'FEMALE' },
  { name: 'hu-HU-Wavenet-C', languageCodes: ['hu-HU'], gender: 'MALE' },
  { name: 'hu-HU-Wavenet-D', languageCodes: ['hu-HU'], gender: 'FEMALE' },
  { name: 'id-ID-Wavenet-A', languageCodes: ['id-ID'], gender: 'MALE' },
  { name: 'id-ID-Wavenet-B', languageCodes: ['id-ID'], gender: 'FEMALE' },
  { name: 'id-ID-Wavenet-C', languageCodes: ['id-ID'], gender: 'MALE' },
  { name: 'id-ID-Wavenet-D', languageCodes: ['id-ID'], gender: 'FEMALE' },
  { name: 'is-IS-Wavenet-A', languageCodes: ['is-IS'], gender: 'MALE' },
  { name: 'is-IS-Wavenet-B', languageCodes: ['is-IS'], gender: 'FEMALE' },
  { name: 'is-IS-Wavenet-C', languageCodes: ['is-IS'], gender: 'MALE' },
  { name: 'is-IS-Wavenet-D', languageCodes: ['is-IS'], gender: 'FEMALE' },
  { name: 'it-IT-Wavenet-A', languageCodes: ['it-IT'], gender: 'MALE' },
  { name: 'it-IT-Wavenet-B', languageCodes: ['it-IT'], gender: 'FEMALE' },
  { name: 'it-IT-Wavenet-C', languageCodes: ['it-IT'], gender: 'MALE' },
  { name: 'it-IT-Wavenet-D', languageCodes: ['it-IT'], gender: 'FEMALE' },
  { name: 'ja-JP-Wavenet-A', languageCodes: ['ja-JP'], gender: 'MALE' },
  { name: 'ja-JP-Wavenet-B', languageCodes: ['ja-JP'], gender: 'FEMALE' },
  { name: 'ja-JP-Wavenet-C', languageCodes: ['ja-JP'], gender: 'MALE' },
  { name: 'ja-JP-Wavenet-D', languageCodes: ['ja-JP'], gender: 'FEMALE' },
  { name: 'ko-KR-Wavenet-A', languageCodes: ['ko-KR'], gender: 'MALE' },
  { name: 'ko-KR-Wavenet-B', languageCodes: ['ko-KR'], gender: 'FEMALE' },
  { name: 'ko-KR-Wavenet-C', languageCodes: ['ko-KR'], gender: 'MALE' },
  { name: 'ko-KR-Wavenet-D', languageCodes: ['ko-KR'], gender: 'FEMALE' },
  { name: 'nb-NO-Wavenet-A', languageCodes: ['nb-NO'], gender: 'MALE' },
  { name: 'nb-NO-Wavenet-B', languageCodes: ['nb-NO'], gender: 'FEMALE' },
  { name: 'nb-NO-Wavenet-C', languageCodes: ['nb-NO'], gender: 'MALE' },
  { name: 'nb-NO-Wavenet-D', languageCodes: ['nb-NO'], gender: 'FEMALE' },
  { name: 'nl-NL-Wavenet-A', languageCodes: ['nl-NL'], gender: 'MALE' },
  { name: 'nl-NL-Wavenet-B', languageCodes: ['nl-NL'], gender: 'FEMALE' },
  { name: 'nl-NL-Wavenet-C', languageCodes: ['nl-NL'], gender: 'MALE' },
  { name: 'nl-NL-Wavenet-D', languageCodes: ['nl-NL'], gender: 'FEMALE' },
  { name: 'pl-PL-Wavenet-A', languageCodes: ['pl-PL'], gender: 'MALE' },
  { name: 'pl-PL-Wavenet-B', languageCodes: ['pl-PL'], gender: 'FEMALE' },
  { name: 'pl-PL-Wavenet-C', languageCodes: ['pl-PL'], gender: 'MALE' },
  { name: 'pl-PL-Wavenet-D', languageCodes: ['pl-PL'], gender: 'FEMALE' },
  { name: 'pt-BR-Wavenet-A', languageCodes: ['pt-BR'], gender: 'MALE' },
  { name: 'pt-BR-Wavenet-B', languageCodes: ['pt-BR'], gender: 'FEMALE' },
  { name: 'pt-BR-Wavenet-C', languageCodes: ['pt-BR'], gender: 'MALE' },
  { name: 'pt-BR-Wavenet-D', languageCodes: ['pt-BR'], gender: 'FEMALE' },
  { name: 'pt-PT-Wavenet-A', languageCodes: ['pt-PT'], gender: 'MALE' },
  { name: 'pt-PT-Wavenet-B', languageCodes: ['pt-PT'], gender: 'FEMALE' },
  { name: 'pt-PT-Wavenet-C', languageCodes: ['pt-PT'], gender: 'MALE' },
  { name: 'pt-PT-Wavenet-D', languageCodes: ['pt-PT'], gender: 'FEMALE' },
  { name: 'ru-RU-Wavenet-A', languageCodes: ['ru-RU'], gender: 'MALE' },
  { name: 'ru-RU-Wavenet-B', languageCodes: ['ru-RU'], gender: 'FEMALE' },
  { name: 'ru-RU-Wavenet-C', languageCodes: ['ru-RU'], gender: 'MALE' },
  { name: 'ru-RU-Wavenet-D', languageCodes: ['ru-RU'], gender: 'FEMALE' },
  { name: 'sk-SK-Wavenet-A', languageCodes: ['sk-SK'], gender: 'MALE' },
  { name: 'sk-SK-Wavenet-B', languageCodes: ['sk-SK'], gender: 'FEMALE' },
  { name: 'sk-SK-Wavenet-C', languageCodes: ['sk-SK'], gender: 'MALE' },
  { name: 'sk-SK-Wavenet-D', languageCodes: ['sk-SK'], gender: 'FEMALE' },
  { name: 'sv-SE-Wavenet-A', languageCodes: ['sv-SE'], gender: 'MALE' },
  { name: 'sv-SE-Wavenet-B', languageCodes: ['sv-SE'], gender: 'FEMALE' },
  { name: 'sv-SE-Wavenet-C', languageCodes: ['sv-SE'], gender: 'MALE' },
  { name: 'sv-SE-Wavenet-D', languageCodes: ['sv-SE'], gender: 'FEMALE' },
  { name: 'th-TH-Wavenet-A', languageCodes: ['th-TH'], gender: 'MALE' },
  { name: 'th-TH-Wavenet-B', languageCodes: ['th-TH'], gender: 'FEMALE' },
  { name: 'th-TH-Wavenet-C', languageCodes: ['th-TH'], gender: 'MALE' },
  { name: 'th-TH-Wavenet-D', languageCodes: ['th-TH'], gender: 'FEMALE' },
  { name: 'tr-TR-Wavenet-A', languageCodes: ['tr-TR'], gender: 'MALE' },
  { name: 'tr-TR-Wavenet-B', languageCodes: ['tr-TR'], gender: 'FEMALE' },
  { name: 'tr-TR-Wavenet-C', languageCodes: ['tr-TR'], gender: 'MALE' },
  { name: 'tr-TR-Wavenet-D', languageCodes: ['tr-TR'], gender: 'FEMALE' },
  { name: 'uk-UA-Wavenet-A', languageCodes: ['uk-UA'], gender: 'MALE' },
  { name: 'uk-UA-Wavenet-B', languageCodes: ['uk-UA'], gender: 'FEMALE' },
  { name: 'uk-UA-Wavenet-C', languageCodes: ['uk-UA'], gender: 'MALE' },
  { name: 'uk-UA-Wavenet-D', languageCodes: ['uk-UA'], gender: 'FEMALE' },
  { name: 'vi-VN-Wavenet-A', languageCodes: ['vi-VN'], gender: 'MALE' },
  { name: 'vi-VN-Wavenet-B', languageCodes: ['vi-VN'], gender: 'FEMALE' },
  { name: 'vi-VN-Wavenet-C', languageCodes: ['vi-VN'], gender: 'MALE' },
  { name: 'vi-VN-Wavenet-D', languageCodes: ['vi-VN'], gender: 'FEMALE' },
  { name: 'yue-HK-Wavenet-A', languageCodes: ['yue-HK'], gender: 'MALE' },
  { name: 'yue-HK-Wavenet-B', languageCodes: ['yue-HK'], gender: 'FEMALE' },
  { name: 'yue-HK-Wavenet-C', languageCodes: ['yue-HK'], gender: 'MALE' },
  { name: 'yue-HK-Wavenet-D', languageCodes: ['yue-HK'], gender: 'FEMALE' },
  // --- END OF OFFICIAL LIST ---
];
